fail_fast: true

repos:

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        language: python
        types: [python]
        args: ["--fix", "--force-exclude"]
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: python
        types: [python]

  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: "mypy ./src/dos2_atlas_generator"
      language: python
      language_version: python3.12
      additional_dependencies: ["mypy",
                                "mypy-extensions"]
      types: [python]
      args: ["--config-file=pyproject.toml"]
      require_serial: true
      verbose: true
      pass_filenames: false

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.338
    hooks:
    - id: pyright

  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: "pylint src/dos2_atlas_generator"
      language: python
      language_version: python3.12
      additional_dependencies: []
      types: [python]
      args: ["--rcfile=pyproject.toml"]
      require_serial: true
      verbose: true
      pass_filenames: false

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.29.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
